---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: capdo-controller-manager
  namespace: capdo-system
spec:
  template:
    spec:
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
        - key: CriticalAddonsOnly
          operator: Exists
