linters:
  disable-all: true
  enable:
    - deadcode
    - goconst
    - gofmt
    - golint
    - gosec
    - govet
    - ineffassign
    - interfacer
    - maligned
    - misspell
    - nakedret
    - prealloc
    - structcheck
    - unconvert
    - varcheck
  # Run with --fast=false for more extensive checks
  fast: true
issues:
  max-same-issues: 0
  max-per-linter: 0
  # List of regexps of issue texts to exclude, empty list by default.
  exclude:
    - Using the variable on range scope `(tc)|(rt)|(tt)|(test)|(testcase)|(testCase)` in function literal
run:
  timeout: 6m
  skip-files:
    - "zz_generated.*\\.go$"
    - ".*_mock\\.go"
