---
apiVersion: cluster.x-k8s.io/v1alpha4
kind: Cluster
metadata:
  name: "${CLUSTER_NAME}"
spec:
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
    kind: DOKSCluster
    name: "${CLUSTER_NAME}"
  controlPlaneRef:
    kind: DOKSControlPlane
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha4
    name: "${CLUSTER_NAME}-control-plane"
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
kind: DOKSCluster
metadata:
  name: "${CLUSTER_NAME}"
spec:
  region: ${DO_REGION}
  version: "${KUBERNETES_VERSION}"
  defaultMachinePoolName: "${CLUSTER_NAME}-mp-0"
---
kind: DOKSControlPlane
apiVersion: controlplane.cluster.x-k8s.io/v1alpha4
metadata:
  name: "${CLUSTER_NAME}-control-plane"
spec:
  clusterName: "${CLUSTER_NAME}"
---
apiVersion: cluster.x-k8s.io/v1alpha4
kind: MachinePool
metadata:
  name: "${CLUSTER_NAME}-mp-0"
spec:
  clusterName: "${CLUSTER_NAME}"
  replicas: ${WORKER_MACHINE_COUNT}
  selector:
    matchLabels:
  template:
    spec:
      clusterName: "${CLUSTER_NAME}"
      bootstrap:
        data: "" # empty string means ignore?
      infrastructureRef:
        name: "${CLUSTER_NAME}-mp-0"
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
        kind: DOKSMachineTemplate
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
kind: DOKSMachineTemplate
metadata:
  name: "${CLUSTER_NAME}-mp-0"
spec:
  template:
    spec:
      size: "${DO_NODE_MACHINE_TYPE}"
